import Head from "next/head";
import Image from "next/image";
import m1 from "../public/m1.jpg";
import m2 from "../public/m2.jpg";
import m3 from "../public/m3.jpg";

import { GiMountains } from "react-icons/gi";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Mountain Club</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" max-w-screen-2xl m-auto">
        <section>
          <div className="bg-[url('../public/main.jpg')] bg-no-repeat bg-cover bg-center">
            <div className="pt-40 md:pt-10 lg:pt-20">
              <GiMountains
                className=" text-white mx-auto h-1/5 w-1/5 md:h-1/5 md:w-1/5 lg:h-36 lg:w-36 lg:mx-auto"
                width={"100%"}
                height={"100%"}
              />
            </div>

            <div className=" mx-auto text-center pt-[65%] md:pt-[60%] lg:pt-[26%]">
              <h2 className="text-3xl mx-10 font-bold text-gray-50 md:text-5xl lg:text-5xl">
                Welcome to Mountain Expeditions Club
              </h2>

              <h4 className="text-xl font-bold pt-20 pb-28 text-white md:pb-24 lg:text-2xl">
                Overseas Expeditions, UK Montain Challenges Private Guiding &
                Instruction
              </h4>
            </div>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320">
              <path
                fill="white"
                fill-opacity="1"
                d="M0,32L720,192L1440,32L1440,320L720,320L0,320Z"
              ></path>
            </svg>
          </div>
        </section>

        <section>
          <div className="bg-white pb-20">
            <div className="text-5xl font-bold mx-auto text-center pb-10">
              <h2>About Us</h2>
            </div>

            <div className="lg:flex lg:flex-row">
              <div className=" mx-10 py-10 leading-8 shadow-2xl rounded-md p-2 md:mx-10 lg:mx-20">
                <p>
                  Lorem ipsum dolor sit, amet consectetur adipisicing elit.
                  Magni nulla ipsum quam soluta est! Vero quisquam aliquid qui
                  vitae corrupti.
                </p>
                <p>
                  Lorem ipsum dolor sit amet consectetur adipisicing elit. Aut
                  doloribus delectus voluptates velit distinctio, vel possimus
                  aperiam sequi ex, dolorum voluptatibus non laborum dicta eius.
                </p>
              </div>

              <div className="mx-10 py-10 leading-8 shadow-2xl rounded-md p-2 md:mx-10 lg:mx-20">
                <p>
                  Lorem ipsum dolor sit, amet consectetur adipisicing elit.
                  Magni nulla ipsum quam soluta est! Vero quisquam aliquid qui
                  vitae corrupti.
                </p>
                <p>
                  Lorem ipsum dolor sit amet consectetur adipisicing elit. Aut
                  doloribus delectus voluptates velit distinctio, vel possimus
                  aperiam sequi ex, dolorum voluptatibus non laborum dicta eius.
                </p>
                <button className="text-xl font-bold text-center text-blue-400 my-5 bg-gray-600 rounded-full py-3 px-10 hover:scale-110 hover:transition-all">
                  Read More
                </button>
              </div>
            </div>
          </div>
        </section>

        <section>

          <div className="h-full w-full bg-[url('../public/t6.png')] bg-no-repeat bg-cover bg-center ">

            <div className="pt-40 md:pt-0 lg:pt-20">
              <GiMountains
                className=" text-gray-400 mx-auto h-1/5 w-1/5 md:h-1/6 md:w-1/6 lg:h-36 lg:w-36 lg:mx-auto"
                width={"100%"}
                height={"100%"}
              />
            </div>

            <div className="flex flex-col text-center">
              <h2 className="text-2xl text-gray-800 font-bold pt-40 md:text-4xl md:text-gray-900 lg:text-4xl lg:pt-60 lg:text-gray-800">
                Expedition leaders
              </h2>

              <p className="mx-10 pt-10 -mb-10 md:-mb-40 text-gray-500 leading-7 md:text-gray-500 lg:text-xl font-medium lg:text-gray-500 lg:pt-20 lg:mx-40 xl:mx-40">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempore
                aliquid nulla iste optio debitis dolore excepturi reiciendis
                totam aliquam nostrum, similique omnis. Magnam obcaecati quo
                quas numquam voluptate cupiditate eaque quidem culpa quaerat?
                Autem nisi voluptates perspiciatis cupiditate sed temporibus
                animi accusantium eius, exercitationem fugiat distinctio, quos
                qui suscipit sint.
              </p>
            </div>
            <svg
              xmlns="http://www.w3.org/2000/svg"
              viewBox="0 0 1440 320"
              className=" opacity-50"
            >
              <path
                fill="black"
                fill-opacity="1"
                d="M0,64L1440,224L1440,320L0,320Z"
              ></path>
            </svg>
          </div>
        </section>

        <section>

          <div className="h-full w-full bg-[url('../public/t6.png')] bg-no-repeat bg-cover bg-center">

            <div className="flex flex-col pb-40 text-gray-100 lg:flex lg:flex-row lg:justify-around backdrop-brightness-50">

              <div className="w-80 h-80 mt-40 mx-auto">
                <Image
                  src={m1}
                  width={"100%"}
                  height={"100%"}
                />
                <h3 className="text-xl text-gray-300 py-5 pl-3 md:text-2xl lg:text-3xl">
                  Expedition Reports
                </h3>
                <p className="pl-3">
                  Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eius
                  cum quis harum placeat. Cum vitae necessitatibus, facilis quas
                  qui autem.
                </p>
                <button className="text-xl font-bold text-center text-blue-400 my-5 bg-gray-600 rounded-md ml-3 py-3 px-10 hover:scale-110 hover:transition-all">
                  READ MORE
                </button>
              </div>

              <div className="w-80 h-80 mt-40 mx-auto mb-20">
                <Image
                  src={m3}
                  width={"100%"}
                  height={"100%"}
                />
                <h3 className="text-xl py-5 pl-3 md:text-2xl lg:text-3xl">
                  Expedition Reports
                </h3>
                <p className="pl-3">
                  Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eius
                  cum quis harum placeat. Cum vitae necessitatibus, facilis quas
                  qui autem.
                </p>
                <button className="text-xl font-bold text-center text-blue-400 my-5 bg-gray-600 rounded-md ml-3 py-3 px-10 hover:scale-110 hover:transition-all">
                  READ MORE
                </button>
              </div>

              <div className="w-80 h-80 mt-40 mx-auto">
                <Image
                  src={m2}
                  width={"100%"}
                  height={"100%"}
                />
                <h3 className="text-xl py-5 pl-3 md:text-2xl lg:text-3xl">
                  Expedition Reports
                </h3>
                <p className="pl-3">
                  Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eius
                  cum quis harum placeat. Cum vitae necessitatibus, facilis quas
                  qui autem.
                </p>
                <button className="text-xl font-bold text-center text-blue-400 my-5 bg-gray-600 rounded-md ml-3 py-3 px-10 hover:scale-110 hover:transition-all">
                  READ MORE
                </button>

              </div>

            </div>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320" className=" opacity-50">
              <path
                fill="black"
                fill-opacity="1"
                d="M0,288L1440,0L1440,0L0,0Z"
              ></path>
            </svg>
          </div>
        </section>

        <section>
          <div className="h-full w-full bg-[url('../public/background.png')] bg-no-repeat bg-cover bg-center pb-40">
            
            <div className=" pb-40 lg:flex lg:flex-row lg:mx-10 lg:gap-16 lg:justify-center">

              <div className="w-80 h-80 md:w-96 md:h-96 lg:w-96 lg:h-96 mt-20 mx-auto">
                <Image
                  src={m1}
                  width={"100%"}
                  height={"100%"}
                />
              </div>

              <div className="w-80 h-80 md:w-96 md:h-96 lg:w-96 lg:h-96 mt-20 mx-auto">
                <Image
                  src={m3}
                  width={"100%"}
                  height={"100%"}
                />
              </div>

              <div className="w-80 h-80 md:w-96 md:h-96 lg:w-96 lg:h-96 mt-20 mx-auto">
                <Image
                  src={m2}
                  width={"100%"}
                  height={"100%"}
                />
              </div>

            </div>

            <div className=" backdrop-brightness-50  pb-20 mx-10 md:mx-40 lg:mx-60">

              <h2 className=" text-white text-center pb-10 text-2xl md:text-4xl lg:text-5xl lg:font-bold ">
                Our Leaders
              </h2>

              <p className=" font-medium text-white px-3 leading-7">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus
                odit tempore sed incidunt sunt, nostrum ab? Nam id ullam
                incidunt rem, omnis temporibus laudantium fuga dolor ex sequi ad
                in ducimus sunt vero! Facere, illo quisquam? Omnis itaque animi
                illum facilis illo temporibus nobis, iste explicabo dignissimos
                atque, voluptatum cum.
              </p>

              <p className=" font-medium text-white px-3 leading-7">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores
                exercitationem, facilis ut, necessitatibus consectetur error
                velit quis nostrum quae repudiandae ipsum. Voluptatibus ex
                voluptatem corrupti.
              </p>

            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
